export const useLimit = () => {
  return {
    basic: {
      name: "Monthly Plan",
      monthlyPrice: 2,
      yearlyPrice: 89,
      paddle: {
        monthlyName: "basic",
        yearlyName: "basic_yearly",
        monthly: "pri_01jg9tgzspc7ccnw2aneaj1320",
        yearly: "pri_01jg9tk8ccmg9bs2acp4vjsqya",
      },
      oem: "Unlimited",
      oemYear: "Unlimited",
      gqq: 2500,
      gqqYear: 25000,
      icl: 5000,
      sl: "Unlimited",
      dqq: true,
      ttq: true,
      utq: true,
      ytq: true,
      ptq: true,
      apq: true,
      mls: true,
      pe: "Unlimited",
    },
    growth: {
      name: "6 Month Plan",
      monthlyPrice: 10.99,
      yearlyPrice: 289,
      paddle: {
        monthlyName: "growth",
        yearlyName: "growth_yearly",
        monthly: "pri_01jg9tmv0rcskgz8vsyp7hw8js",
        yearly: "pri_01jg9tr63qhgp92dx513j2k866",
      },
      oem: "Unlimited",
      oemYear: "Unlimited",
      gqq: 10000,
      gqqYear: 100000,
      icl: 10000,
      sl: "Unlimited",
      dqq: true,
      ttq: true,
      utq: true,
      ytq: true,
      ptq: true,
      apq: true,
      mls: true,
      pe: "Unlimited",
    },
    professional: {
      name: "Yearly Plan",
      monthlyPrice: 19.99,
      yearlyPrice: 589,
      paddle: {
        monthlyName: "professional",
        yearlyName: "professional_yearly",
        monthly: "pri_01jg9tstpv279vdzp7rfkpp7f3",
        yearly: "pri_01jg9tvat2ndjyzs8jpxjbfnk4",
      },
      oem: "Unlimited",
      oemYear: "Unlimited",
      gqq: 25000,
      gqqYear: 250000,
      icl: 20000,
      sl: "Unlimited",
      dqq: true,
      ttq: true,
      utq: true,
      ytq: true,
      ptq: true,
      apq: true,
      mls: true,
      pe: "Unlimited",
    },
    enterprise: {
      name: "Free Trial",
      monthlyPrice: 0,
      yearlyPrice: 0,
      oem: "Not Allowed",
      oemYear: "Not Allowed",
      gqq: 10,
      gqqYear: "Not Allowed",
      icl: 100,
      sl: "Not Allowed",
      dqq: false,
      ttq: true,
      utq: true,
      ytq: true,
      ptq: true,
      apq: true,
      mls: true,
      pe: "Unlimited",
    },
  };
};
