export const useLimit = () => {
  return {
    starter: {
      name: "Starter Plan",
      monthlyPrice: 9,
      yearlyPrice: 89,
      paddle: {
        monthlyName: "starter_monthly",
        yearlyName: "starter_yearly",
        monthly: "pri_01jfjxq5n6bxeddz7s54f64trs",
        yearly: "pri_01jfjxszwcggm9bcan4jzv55y9",
      },
      oem: 50,
      oemYear: 500,
      gqq: 2500,
      gqqYear: 25000,
      icl: 5000,
      sl: "Unlimited",
      dqq: true,
      ttq: true,
      utq: true,
      ytq: true,
      ptq: true,
      apq: true,
      mls: true,
    },
    growth: {
      name: "Growth Plan",
      monthlyPrice: 29,
      yearlyPrice: 289,
      paddle: {
        monthlyName: "growth_monthly",
        yearlyName: "growth_yearly",
        monthly: "pri_01jfjxyfnjrkgjexstgnm4zjx4",
        yearly: "pri_01jfjy17tpf4d3z7ahjk0vjxtg",
      },
      oem: 200,
      oemYear: 2000,
      gqq: 10000,
      gqqYear: 100000,
      icl: 10000,
      sl: "Unlimited",
      dqq: true,
      ttq: true,
      utq: true,
      ytq: true,
      ptq: true,
      apq: true,
      mls: true,
    },
    professional: {
      name: "Professional Plan",
      monthlyPrice: 59,
      yearlyPrice: 589,
      paddle: {
        monthlyName: "professional_monthly",
        yearlyName: "professional_yearly",
        monthly: "pri_01jfjy3m34kw4m7be10d2ynwx5",
        yearly: "pri_01jfjy4y2z790pjdehvvdn1tfm",
      },
      oem: 500,
      oemYear: 5000,
      gqq: 25000,
      gqqYear: 250000,
      icl: 20000,
      sl: "Unlimited",
      dqq: true,
      ttq: true,
      utq: true,
      ytq: true,
      ptq: true,
      apq: true,
      mls: true,
    },
    free: {
      name: "Free trial",
      monthlyPrice: 0,
      yearlyPrice: 0,
      oem: "Not allow",
      oemYear: "Not allow",
      gqq: 25,
      gqqYear: 25,
      icl: 100,
      sl: "Not allow",
      dqq: true,
      ttq: true,
      utq: true,
      ytq: true,
      ptq: true,
      apq: true,
      mls: true,
    },
  };
};
